# Generated by Django 4.1.6 on 2023-09-22 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolClasses',
            fields=[
                ('class_name', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
    ]
